version: '2'
services:
  db:
    image: mysql:5.7
    container_name: myshop2-mysql
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3305:3305"
  php:
    image: webdevops/php:7.4
    container_name: myshop2-php
    volumes:
      - "./:/app"
    working_dir: '/app'
  nginx:
    depends_on:
      - php
    image: webdevops/nginx
    container_name: myshop2-nginx
    environment:
      WEB_DOCUMENT_ROOT: /app
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php:9000
    volumes:
      - "./:/app"
    ports:
      - "80:80"